
Line 4 Error (R4) : Stack Overflow 
In function test() in file stack/rec_overflow.ring
called from line 1  in file stack/rec_overflow.ring 
---{ Recursion Depth: 999 }---
